# -*- coding: utf-8 -*-
"""Wildlife Intrusion  p.model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nVFW6EnpTANjSme3XmyHZ6a42vtWFqxL
"""

# ================= ELEPHANT + HUMAN VIDEO DETECTION (FINAL UPDATED VERSION) =================

# 1. Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

# 2. Install required libraries
!pip install -q ultralytics opencv-python

# 3. Imports
from ultralytics import YOLO
import cv2
import os

# 4. Load YOLOv8 pre-trained model
model = YOLO("yolov8n.pt")

# 5. EXACT Google Drive paths (NO TRAILING SPACES)
project_folder = "/content/drive/MyDrive/Elephant_Project_Videos"
input_folder   = "/content/drive/MyDrive/Elephant_Project_Videos/Night_time "
output_folder  = "/content/drive/MyDrive/Elephant_Video_Output/Night_time "

# 6. Safety checks
if not os.path.exists(project_folder):
    raise FileNotFoundError("❌ Elephant_Project_Videos folder not found")

if not os.path.exists(input_folder):
    print("📂 Folders found:", os.listdir(project_folder))
    raise FileNotFoundError("❌ Night_time folder not found (check spelling & case)")

os.makedirs(output_folder, exist_ok=True)

print("📂 Reading videos from:", input_folder)

# 7. Confidence thresholds (IMPORTANT)
ELEPHANT_CONF = 0.45
HUMAN_CONF    = 0.60

# 8. Process each video
for video_name in os.listdir(input_folder):

    if not video_name.lower().endswith(".mp4"):
        continue

    video_path = os.path.join(input_folder, video_name)
    cap = cv2.VideoCapture(video_path)

    width  = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
    fps    = cap.get(cv2.CAP_PROP_FPS)

    output_path = os.path.join(output_folder, video_name)
    fourcc = cv2.VideoWriter_fourcc(*'mp4v')
    out = cv2.VideoWriter(output_path, fourcc, fps, (width, height))

    while cap.isOpened():
        ret, frame = cap.read()
        if not ret:
            break

        results = model(frame)
        elephant_found = False

        for r in results:
            for box in r.boxes:
                cls   = int(box.cls[0])
                conf  = float(box.conf[0])
                label = model.names[cls]
                x1, y1, x2, y2 = map(int, box.xyxy[0])

                # ELEPHANT detection
                if label == "elephant" and conf >= ELEPHANT_CONF:
                    elephant_found = True
                    cv2.rectangle(frame, (x1, y1), (x2, y2),
                                  (0, 255, 0), 2)
                    cv2.putText(frame,
                                f"Elephant {conf:.2f}",
                                (x1, y1 - 10),
                                cv2.FONT_HERSHEY_SIMPLEX,
                                0.9,
                                (0, 255, 0),
                                2)

                # HUMAN detection (stricter threshold)
                elif label == "person" and conf >= HUMAN_CONF:
                    cv2.rectangle(frame, (x1, y1), (x2, y2),
                                  (255, 0, 0), 2)
                    cv2.putText(frame,
                                f"Human {conf:.2f}",
                                (x1, y1 - 10),
                                cv2.FONT_HERSHEY_SIMPLEX,
                                0.9,
                                (255, 0, 0),
                                2)

        # 🚨 CAUTION ALERT
        if elephant_found:
            cv2.putText(frame,
                        "CAUTION: ELEPHANT DETECTED",
                        (30, 50),
                        cv2.FONT_HERSHEY_SIMPLEX,
                        1.2,
                        (0, 0, 255),
                        3)

        out.write(frame)

    cap.release()
    out.release()

    print(f"✅ Processed: {video_name}")

print("🎉 ALL NIGHT-TIME VIDEOS PROCESSED SUCCESSFULLY!")

# ================= SINGLE VIDEO ELEPHANT + HUMAN DETECTION =================

from google.colab import drive
drive.mount('/content/drive')

!pip install -q ultralytics opencv-python

from ultralytics import YOLO
import cv2
import os

# Load model
model = YOLO("yolov8n.pt")

# ---------- INPUT & OUTPUT (SINGLE FILE) ----------
# Please ensure the video file exists at this path in your Google Drive.
# For example, if your video is in 'My Drive/videos/my_elephant_video.mp4', update the path accordingly.
input_video  = "/content/drive/MyDrive/Elephant_Project_Videos/Elephant_Human/EDH2.mp4"
output_video = "/content/drive/MyDrive/EDH2_output.mp4"

# Safety check
if not os.path.exists(input_video):
    raise FileNotFoundError("❌ EDH6.mp4 not found. Check filename & path.")

cap = cv2.VideoCapture(input_video)

fps = cap.get(cv2.CAP_PROP_FPS)
if fps == 0 or fps is None:
    fps = 25

width  = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))

fourcc = cv2.VideoWriter_fourcc(*'mp4v')
out = cv2.VideoWriter(output_video, fourcc, fps, (width, height))

# Confidence thresholds
ELEPHANT_CONF = 0.45
HUMAN_CONF = 0.60

frame_count = 0

while True:
    ret, frame = cap.read()
    if not ret:
        break

    frame_count += 1
    results = model(frame)
    elephant_found = False

    for r in results:
        for box in r.boxes:
            cls   = int(box.cls[0])
            conf  = float(box.conf[0])
            label = model.names[cls]
            x1, y1, x2, y2 = map(int, box.xyxy[0])

            if label == "elephant" and conf >= ELEPHANT_CONF:
                elephant_found = True
                cv2.rectangle(frame, (x1, y1), (x2, y2), (0,255,0), 2)
                cv2.putText(frame, "Elephant",
                            (x1, y1-10),
                            cv2.FONT_HERSHEY_SIMPLEX,
                            0.9, (0,255,0), 2)

            elif label == "person" and conf >= HUMAN_CONF:
                cv2.rectangle(frame, (x1, y1), (x2, y2), (255,0,0), 2)
                cv2.putText(frame, "Human",
                            (x1, y1-10),
                            cv2.FONT_HERSHEY_SIMPLEX,
                            0.9, (255,0,0), 2)

    if elephant_found:
        cv2.putText(frame,
                    "CAUTION: ELEPHANT DETECTED",
                    (30,50),
                    cv2.FONT_HERSHEY_SIMPLEX,
                    1.1, (0,0,255), 3)

    out.write(frame)

cap.release()
out.release()

print("✅ DONE!")
print("📁 Output saved as:", output_video)
print("🎞 Frames processed:", frame_count)

!pip install -q ultralytics opencv-python

from ultralytics import YOLO
import cv2
import time

model = YOLO("yolov8n.pt")

video_path = "/content/Farm_Scene_Video_Generation.mp4"
cap = cv2.VideoCapture(video_path)

ELEPHANT_CONF = 0.45
HUMAN_CONF = 0.60

total_frames = 0
elephant_frames = 0
human_frames = 0
coexist_frames = 0
false_alerts = 0

start_time = time.time()
prev_elephant = False

while cap.isOpened():
    ret, frame = cap.read()
    if not ret:
        break

    total_frames += 1
    results = model(frame)

    elephant_found = False
    human_found = False

    for r in results:
        for box in r.boxes:
            label = model.names[int(box.cls[0])]
            conf = float(box.conf[0])

            if label == "elephant" and conf >= ELEPHANT_CONF:
                elephant_found = True
            if label == "person" and conf >= HUMAN_CONF:
                human_found = True

    if elephant_found:
        elephant_frames += 1
    if human_found:
        human_frames += 1
    if elephant_found and human_found:
        coexist_frames += 1

    # False alert = elephant appears for only 1 frame
    if elephant_found and not prev_elephant:
        false_alerts += 1

    prev_elephant = elephant_found

cap.release()
end_time = time.time()

fps = total_frames / (end_time - start_time)

#custom
from ultralytics import YOLO
import cv2
import os

# ---------------- CONFIG ----------------
input_video  = "/content/Farm_Scene_Video_Generation.mp4"
output_video = "/content/drive/MyDrive/output_elephant_detected.mp4"

ELEPHANT_CONF = 0.45
# ----------------------------------------

# Load YOLOv8 model
model = YOLO("yolov8n.pt")

# Safety check
if not os.path.exists(input_video):
    raise FileNotFoundError("❌ Input video not found")

cap = cv2.VideoCapture(input_video)

fps = cap.get(cv2.CAP_PROP_FPS)
if fps == 0:
    fps = 25

width  = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))

fourcc = cv2.VideoWriter_fourcc(*'mp4v')
out = cv2.VideoWriter(output_video, fourcc, fps, (width, height))

frame_count = 0
elephant_frames = 0

while True:
    ret, frame = cap.read()
    if not ret:
        break

    frame_count += 1
    results = model(frame, verbose=False)

    elephant_found = False

    for r in results:
        for box in r.boxes:
            cls   = int(box.cls[0])
            conf  = float(box.conf[0])
            label = model.names[cls]

            if label == "elephant" and conf >= ELEPHANT_CONF:
                elephant_found = True
                x1, y1, x2, y2 = map(int, box.xyxy[0])

                cv2.rectangle(frame, (x1, y1), (x2, y2),
                              (0, 255, 0), 2)
                cv2.putText(frame,
                            f"Elephant {conf:.2f}",
                            (x1, y1 - 10),
                            cv2.FONT_HERSHEY_SIMPLEX,
                            0.9,
                            (0, 255, 0),
                            2)

    if elephant_found:
        elephant_frames += 1
        cv2.putText(frame,
                    "ELEPHANT DETECTED",
                    (30, 50),
                    cv2.FONT_HERSHEY_SIMPLEX,
                    1.1,
                    (0, 0, 255),
                    3)

    out.write(frame)

cap.release()
out.release()

print("✅ Processing complete")
print("🎞 Total frames:", frame_count)
print("🐘 Frames with elephant:", elephant_frames)
print("📁 Output saved at:", output_video)

print("📊 VIDEO-BASED RESULTS")
print("----------------------")
print(f"Total Frames           : {total_frames}")
print(f"Elephant Detected (%)  : {elephant_frames/total_frames*100:.2f}%")
print(f"Human Detected (%)     : {human_frames/total_frames*100:.2f}%")
print(f"Co-occurrence (%)      : {coexist_frames/total_frames*100:.2f}%")
print(f"False Alerts (count)   : {false_alerts}")
print(f"Processing Speed (FPS) : {fps:.2f}")

# ================= SINGLE VIDEO ELEPHANT + HUMAN DETECTION =================

from google.colab import drive
drive.mount('/content/drive')

!pip install -q ultralytics opencv-python

from ultralytics import YOLO
import cv2
import os

# Load YOLO model
model = YOLO("yolov8n.pt")

# -------- INPUT & OUTPUT VIDEO --------
input_video  = "/content/drive/MyDrive/Elephant_Project_Videos/ED91.mp4"
output_video = "/content/drive/MyDrive/Elephant_Project_Videos/ED91_output.mp4"

# Check video exists
if not os.path.exists(input_video):
    raise FileNotFoundError("❌ ED91.mp4 not found")

cap = cv2.VideoCapture(input_video)
print("Video opened:", cap.isOpened())

# Video properties
fps = cap.get(cv2.CAP_PROP_FPS)
if fps == 0 or fps is None:
    fps = 25

width  = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))

fourcc = cv2.VideoWriter_fourcc(*'mp4v')
out = cv2.VideoWriter(output_video, fourcc, fps, (width, height))

# -------- CONFIDENCE THRESHOLDS (FIXED VALUES) --------
ELEPHANT_CONF = 0.59   # Elephant detection confidence
HUMAN_CONF    = 0.65   # Human detection confidence

frames = 0

while True:
    ret, frame = cap.read()
    if not ret:
        break

    frames += 1
    results = model(frame)
    elephant_found = False

    for r in results:
        for box in r.boxes:
            cls = int(box.cls[0])
            conf = float(box.conf[0])
            label = model.names[cls]
            x1, y1, x2, y2 = map(int, box.xyxy[0])

            if label == "elephant" and conf >= ELEPHANT_CONF:
                elephant_found = True
                cv2.rectangle(frame, (x1, y1), (x2, y2), (0,255,0), 2)
                cv2.putText(frame, f"Elephant {conf:.2f}",
                            (x1, y1-10),
                            cv2.FONT_HERSHEY_SIMPLEX,
                            0.9, (0,255,0), 2)

            elif label == "person" and conf >= HUMAN_CONF:
                cv2.rectangle(frame, (x1, y1), (x2, y2), (255,0,0), 2)
                cv2.putText(frame, f"Human {conf:.2f}",
                            (x1, y1-10),
                            cv2.FONT_HERSHEY_SIMPLEX,
                            0.9, (255,0,0), 2)

    if elephant_found:
        cv2.putText(frame,
                    "CAUTION: ELEPHANT DETECTED",
                    (30,50),
                    cv2.FONT_HERSHEY_SIMPLEX,
                    1.1, (0,0,255), 3)

    out.write(frame)

cap.release()
out.release()

print("✅ DONE")
print("Frames processed:", frames)
print("Output saved as:", output_video)

# ================= SINGLE VIDEO ELEPHANT + HUMAN DETECTION WITH SCORE =================

from google.colab import drive
drive.mount('/content/drive')

!pip install -q ultralytics opencv-python

from ultralytics import YOLO
import cv2
import os

# 1️⃣ Load YOLO model
model = YOLO("yolov8n.pt")   # later you will replace with your trained model

# 2️⃣ Input and output video paths
input_video  = "/content/drive/MyDrive/Elephant_Project_Videos/Elephant_Human/EDH73.mp4"
output_video = "/content/drive/MyDrive/Elephant_Project_Videos/EDH73_output.mp4"

# 3️⃣ Check video exists
if not os.path.exists(input_video):
    raise FileNotFoundError("❌ Video not found")

# 4️⃣ Open video
cap = cv2.VideoCapture(input_video)
print("Video opened:", cap.isOpened())

# 5️⃣ Video properties
fps = cap.get(cv2.CAP_PROP_FPS)
if fps == 0 or fps is None:
    fps = 25

width  = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))

# 6️⃣ Create output video writer
fourcc = cv2.VideoWriter_fourcc(*'mp4v')
out = cv2.VideoWriter(output_video, fourcc, fps, (width, height))

# 7️⃣ Confidence thresholds
ELEPHANT_CONF = 0.45
HUMAN_CONF    = 0.60

frame_count = 0

# 8️⃣ Process video frame by frame
while True:
    ret, frame = cap.read()
    if not ret:
        break

    frame_count += 1
    results = model(frame)

    elephant_found = False

    for r in results:
        for box in r.boxes:
            cls   = int(box.cls[0])
            conf  = float(box.conf[0])
            label = model.names[cls]
            x1, y1, x2, y2 = map(int, box.xyxy[0])

            # 🐘 Elephant detection
            if label == "elephant" and conf >= ELEPHANT_CONF:
                elephant_found = True
                cv2.rectangle(frame, (x1, y1), (x2, y2), (0,255,0), 2)
                cv2.putText(frame,
                            f"Elephant {conf:.2f}",
                            (x1, y1 - 10),
                            cv2.FONT_HERSHEY_SIMPLEX,
                            0.9, (0,255,0), 2)

            # 🧍 Human detection
            elif label == "person" and conf >= HUMAN_CONF:
                cv2.rectangle(frame, (x1, y1), (x2, y2), (255,0,0), 2)
                cv2.putText(frame,
                            f"Human {conf:.2f}",
                            (x1, y1 - 10),
                            cv2.FONT_HERSHEY_SIMPLEX,
                            0.9, (255,0,0), 2)

    # 🚨 Alert text
    if elephant_found:
        cv2.putText(frame,
                    "CAUTION: ELEPHANT DETECTED",
                    (30, 50),
                    cv2.FONT_HERSHEY_SIMPLEX,
                    1.1, (0,0,255), 3)

    out.write(frame)

# 9️⃣ Release everything
cap.release()
out.release()

print("✅ DONE")
print("Frames processed:", frame_count)
print("📁 Output saved at:", output_video)

# ================= SINGLE VIDEO ELEPHANT + HUMAN DETECTION (FINE-TUNED PIPELINE) =================

from google.colab import drive
drive.mount('/content/drive')

!pip install -q ultralytics opencv-python

from ultralytics import YOLO
import cv2
import os

# -------------------------------------------------
#  Load YOLO pretrained model (later replace with best.pt)
# -------------------------------------------------
model = YOLO("yolov8n.pt")

# -------------------------------------------------
#  Input & Output video paths
# -------------------------------------------------
input_video  = "/content/drive/MyDrive/Elephant_Project_Videos/ED91.mp4"
output_video = "/content/drive/MyDrive/Elephant_Project_Videos/ED91_output_finetuned.mp4"

if not os.path.exists(input_video):
    raise FileNotFoundError("❌ Input video not found")

# -------------------------------------------------
#  Open video
# -------------------------------------------------
cap = cv2.VideoCapture(input_video)
print("Video opened:", cap.isOpened())

fps = cap.get(cv2.CAP_PROP_FPS)
if fps == 0 or fps is None:
    fps = 25

width  = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))

fourcc = cv2.VideoWriter_fourcc(*'mp4v')
out = cv2.VideoWriter(output_video, fourcc, fps, (width, height))

# -------------------------------------------------
# Fine-tuned confidence thresholds
# -------------------------------------------------
ELEPHANT_CONF = 0.60   # stricter = fewer false positives
HUMAN_CONF    = 0.70

# -------------------------------------------------
#  Low-light enhancement function (IMPORTANT)
# -------------------------------------------------
def enhance_frame(frame):
    lab = cv2.cvtColor(frame, cv2.COLOR_BGR2LAB)
    l, a, b = cv2.split(lab)
    clahe = cv2.createCLAHE(clipLimit=2.0, tileGridSize=(8,8))
    l2 = clahe.apply(l)
    merged = cv2.merge((l2, a, b))
    return cv2.cvtColor(merged, cv2.COLOR_LAB2BGR)

# -------------------------------------------------
#  Temporal consistency counter
# -------------------------------------------------
elephant_counter = 0
TEMPORAL_THRESHOLD = 3   # elephant must appear in 3 frames

frame_count = 0

# -------------------------------------------------
#  Process video frame by frame
# -------------------------------------------------
while True:
    ret, frame = cap.read()
    if not ret:
        break

    frame_count += 1

    # Enhance night-time frame
    frame = enhance_frame(frame)

    results = model(frame)

    elephant_detected = False
    human_detected = False

    for r in results:
        for box in r.boxes:
            cls   = int(box.cls[0])
            conf  = float(box.conf[0])
            label = model.names[cls]
            x1, y1, x2, y2 = map(int, box.xyxy[0])

            #  Elephant detection
            if label == "elephant" and conf >= ELEPHANT_CONF:
                elephant_counter += 1
                if elephant_counter >= TEMPORAL_THRESHOLD:
                    elephant_detected = True
                    cv2.rectangle(frame, (x1, y1), (x2, y2), (0,255,0), 2)
                    cv2.putText(frame,
                                f"Elephant {conf:.2f}",
                                (x1, y1 - 10),
                                cv2.FONT_HERSHEY_SIMPLEX,
                                0.9, (0,255,0), 2)

            #  Human detection
            elif label == "person" and conf >= HUMAN_CONF:
                human_detected = True
                cv2.rectangle(frame, (x1, y1), (x2, y2), (255,0,0), 2)
                cv2.putText(frame,
                            f"Human {conf:.2f}",
                            (x1, y1 - 10),
                            cv2.FONT_HERSHEY_SIMPLEX,
                            0.9, (255,0,0), 2)

    # Reset temporal counter if elephant not detected
    if not elephant_detected:
        elephant_counter = 0

    # -------------------------------------------------
    # Alert logic (SYSTEM CONTRIBUTION)
    # -------------------------------------------------
    if elephant_detected and human_detected:
        cv2.putText(frame,
                    "DANGER: ELEPHANT & HUMAN",
                    (30, 50),
                    cv2.FONT_HERSHEY_SIMPLEX,
                    1.2, (0,0,255), 3)

    elif elephant_detected:
        cv2.putText(frame,
                    "CAUTION: ELEPHANT DETECTED",
                    (30, 50),
                    cv2.FONT_HERSHEY_SIMPLEX,
                    1.2, (0,0,255), 3)

    out.write(frame)

# -------------------------------------------------
#  Release everything
# -------------------------------------------------
cap.release()
out.release()

print("✅ PROCESS COMPLETED SUCCESSFULLY")
print("Frames processed:", frame_count)
print("📁 Output saved at:", output_video)

# ================= SINGLE VIDEO ELEPHANT + HUMAN DETECTION WITH SCORE =================

from google.colab import drive
drive.mount('/content/drive')

!pip install -q ultralytics opencv-python

from ultralytics import YOLO
import cv2
import os

# -------------------------------------------------
# 1️⃣ Load YOLO pretrained model (same elephant code)
# -------------------------------------------------
model = YOLO("yolov8n.pt")   # later replace with best.pt

# -------------------------------------------------
# 2️⃣ Input & Output video paths (ONLY CHANGE IS HERE)
# -------------------------------------------------
input_video  = "/content/drive/MyDrive/tiger.mp4"
output_video = "/content/drive/MyDrive/tiger_output.mp4"

# -------------------------------------------------
# 3️⃣ Safety check
# -------------------------------------------------
if not os.path.exists(input_video):
    raise FileNotFoundError("❌ tiger.mp4 not found in MyDrive")

# -------------------------------------------------
# 4️⃣ Open video
# -------------------------------------------------
cap = cv2.VideoCapture(input_video)
print("Video opened:", cap.isOpened())

fps = cap.get(cv2.CAP_PROP_FPS)
if fps == 0 or fps is None:
    fps = 25

width  = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))

# -------------------------------------------------
# 5️⃣ Output video writer
# -------------------------------------------------
fourcc = cv2.VideoWriter_fourcc(*'mp4v')
out = cv2.VideoWriter(output_video, fourcc, fps, (width, height))

# -------------------------------------------------
# 6️⃣ Confidence thresholds (same as elephant code)
# -------------------------------------------------
ELEPHANT_CONF = 0.60
HUMAN_CONF    = 0.70

frame_count = 0

# -------------------------------------------------
# 7️⃣ Process video frame by frame
# -------------------------------------------------
while True:
    ret, frame = cap.read()
    if not ret:
        break

    frame_count += 1
    results = model(frame)

    elephant_found = False

    for r in results:
        for box in r.boxes:
            cls   = int(box.cls[0])
            conf  = float(box.conf[0])
            label = model.names[cls]
            x1, y1, x2, y2 = map(int, box.xyxy[0])

            # 🐘 ELEPHANT detection (same logic)
            if label == "elephant" and conf >= ELEPHANT_CONF:
                elephant_found = True
                cv2.rectangle(frame, (x1, y1), (x2, y2), (0,255,0), 2)
                cv2.putText(frame,
                            f"Elephant {conf:.2f}",
                            (x1, y1 - 10),
                            cv2.FONT_HERSHEY_SIMPLEX,
                            0.9, (0,255,0), 2)

            # 🧍 HUMAN detection (same logic)
            elif label == "person" and conf >= HUMAN_CONF:
                cv2.rectangle(frame, (x1, y1), (x2, y2), (255,0,0), 2)
                cv2.putText(frame,
                            f"Human {conf:.2f}",
                            (x1, y1 - 10),
                            cv2.FONT_HERSHEY_SIMPLEX,
                            0.9, (255,0,0), 2)

    # 🚨 Alert logic (same as elephant code)
    if elephant_found:
        cv2.putText(frame,
                    "CAUTION: ELEPHANT DETECTED",
                    (30, 50),
                    cv2.FONT_HERSHEY_SIMPLEX,
                    1.1, (0,0,255), 3)

    out.write(frame)

# -------------------------------------------------
# 8️⃣ Release everything
# -------------------------------------------------
cap.release()
out.release()

print("✅ DONE")
print("Frames processed:", frame_count)
print("📁 Output saved at:", output_video)

# ================= ELEPHANT + HUMAN DETECTION (FALSE HUMAN FIXED) =================

from google.colab import drive
drive.mount('/content/drive')

!pip install -q ultralytics opencv-python

from ultralytics import YOLO
import cv2
import os

# -------------------------------------------------
# 1️⃣ Load YOLO pretrained model
# -------------------------------------------------
model = YOLO("yolov8n.pt")

# -------------------------------------------------
# 2️⃣ Automatically find tiger.mp4 anywhere in MyDrive
# -------------------------------------------------
def find_video(root, filename):
    for root_dir, _, files in os.walk(root):
        if filename in files:
            return os.path.join(root_dir, filename)
    return None

input_video = find_video("/content/drive/MyDrive", "tiger.mp4")

if input_video is None:
    raise FileNotFoundError("❌ tiger.mp4 not found anywhere in MyDrive")

output_video = input_video.replace(".mp4", "_output.mp4")

print("✅ Found video at:", input_video)

# -------------------------------------------------
# 3️⃣ Open video
# -------------------------------------------------
cap = cv2.VideoCapture(input_video)
print("Video opened:", cap.isOpened())

fps = cap.get(cv2.CAP_PROP_FPS)
if fps == 0 or fps is None:
    fps = 25

width  = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))

# -------------------------------------------------
# 4️⃣ Output video writer
# -------------------------------------------------
fourcc = cv2.VideoWriter_fourcc(*'mp4v')
out = cv2.VideoWriter(output_video, fourcc, fps, (width, height))

# -------------------------------------------------
# 5️⃣ Confidence thresholds
# -------------------------------------------------
ELEPHANT_CONF = 0.60
HUMAN_CONF    = 0.75   # stricter human confidence

frame_count = 0

# -------------------------------------------------
# 6️⃣ Process video frame by frame
# -------------------------------------------------
while True:
    ret, frame = cap.read()
    if not ret:
        break

    frame_count += 1
    results = model(frame)

    elephant_found = False

    for r in results:
        for box in r.boxes:
            cls   = int(box.cls[0])
            conf  = float(box.conf[0])
            label = model.names[cls]
            x1, y1, x2, y2 = map(int, box.xyxy[0])

            box_width  = x2 - x1
            box_height = y2 - y1
            aspect_ratio = box_height / (box_width + 1e-6)

            # 🐘 ELEPHANT detection
            if label == "elephant" and conf >= ELEPHANT_CONF:
                elephant_found = True
                cv2.rectangle(frame, (x1, y1), (x2, y2), (0,255,0), 2)
                cv2.putText(frame,
                            f"Elephant {conf:.2f}",
                            (x1, y1 - 10),
                            cv2.FONT_HERSHEY_SIMPLEX,
                            0.9, (0,255,0), 2)

            # 🧍 HUMAN detection (FALSE POSITIVE FILTER APPLIED)
            elif label == "person" and conf >= HUMAN_CONF:
                # Human shape constraints
                if box_height < 0.9 * height and aspect_ratio > 1.3:
                    cv2.rectangle(frame, (x1, y1), (x2, y2), (255,0,0), 2)
                    cv2.putText(frame,
                                f"Human {conf:.2f}",
                                (x1, y1 - 10),
                                cv2.FONT_HERSHEY_SIMPLEX,
                                0.9, (255,0,0), 2)

    # 🚨 Alert logic
    if elephant_found:
        cv2.putText(frame,
                    "CAUTION: ELEPHANT DETECTED",
                    (30, 50),
                    cv2.FONT_HERSHEY_SIMPLEX,
                    1.1, (0,0,255), 3)

    out.write(frame)

# -------------------------------------------------
# 7️⃣ Release everything
# -------------------------------------------------
cap.release()
out.release()

print("✅ DONE")
print("Frames processed:", frame_count)
print("📁 Output saved at:", output_video)

# ============================
# Mount Google Drive
# ============================
from google.colab import drive
drive.mount('/content/drive')

# ============================
# Install dependencies
# ============================
!pip install -q ultralytics opencv-python

from ultralytics import YOLO
import cv2
import os

# ============================
# Load YOLOv8
# ============================
model = YOLO("yolov8n.pt")

# ============================
# Input / Output video
# ============================
input_video = "/content/drive/MyDrive/EDH1.mp4"
output_video = "/content/drive/MyDrive/EDH1_output.mp4"

cap = cv2.VideoCapture(input_video)

fps = cap.get(cv2.CAP_PROP_FPS)
if fps == 0:
    fps = 25

w = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
h = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))

out = cv2.VideoWriter(
    output_video,
    cv2.VideoWriter_fourcc(*'mp4v'),
    fps,
    (w, h)
)

# ============================
# YOLO classes
# ============================
wild_animals = [
    "elephant","bear","zebra","giraffe",
    "horse","sheep","cow","dog","cat","bird"
]

human_objects = ["car","truck","bus","motorbike","bicycle"]

# ============================
# Process video
# ============================
while True:
    ret, frame = cap.read()
    if not ret:
        break

    results = model(frame, verbose=False)

    wildlife = False
    human = False
    habitat = False

    for r in results:
        for box in r.boxes:
            cls = int(box.cls[0])
            conf = float(box.conf[0])
            label = model.names[cls]

            x1, y1, x2, y2 = map(int, box.xyxy[0])

            # Wildlife
            if label in wild_animals and conf > 0.4:
                wildlife = True
                cv2.rectangle(frame, (x1,y1), (x2,y2), (0,255,0), 2)
                cv2.putText(frame, label, (x1,y1-5),
                            cv2.FONT_HERSHEY_SIMPLEX, 0.6, (0,255,0), 2)

            # Human
            if label == "person" and conf > 0.6:
                human = True
                cv2.rectangle(frame, (x1,y1), (x2,y2), (255,0,0), 2)
                cv2.putText(frame, "Human", (x1,y1-5),
                            cv2.FONT_HERSHEY_SIMPLEX, 0.6, (255,0,0), 2)

            # Human habitat objects
            if label in human_objects and conf > 0.5:
                habitat = True
                cv2.rectangle(frame, (x1,y1), (x2,y2), (0,255,255), 2)
                cv2.putText(frame, label, (x1,y1-5),
                            cv2.FONT_HERSHEY_SIMPLEX, 0.6, (0,255,255), 2)

    # ============================
    # Intrusion Decision
    # ============================
    status = "NORMAL"

    if wildlife and not human:
        status = "NO INTRUSION"
    elif wildlife and human and not habitat:
        status = "PARTIAL INTRUSION"
    elif wildlife and human and habitat:
        status = "INTRUSION"

    cv2.putText(frame, status, (30,40),
                cv2.FONT_HERSHEY_SIMPLEX, 1, (0,0,255), 3)

    out.write(frame)

cap.release()
out.release()

print("DONE")
print("Saved:", output_video)

# ============================
# Mount Google Drive
# ============================
from google.colab import drive
drive.mount('/content/drive')

# ============================
# Install dependencies
# ============================
!pip install -q ultralytics opencv-python

from ultralytics import YOLO
import cv2
import os

# ============================
# Load YOLOv8
# ============================
model = YOLO("yolov8n.pt")

# ============================
# Videos list
# ============================
video_names = ["EDH1.mp4", "EDH2.mp4", "EDH3.mp4", "EDH5.mp4"]

base_path = "/content/drive/MyDrive"

# ============================
# YOLO classes
# ============================
wild_animals = [
    "elephant","bear","zebra","giraffe",
    "horse","sheep","cow","dog","cat","bird"
]

human_objects = ["car","truck","bus","motorbike","bicycle"]

# ============================
# Process each video
# ============================
for vid in video_names:

    input_video = os.path.join(base_path, vid)
    output_video = input_video.replace(".mp4", "_output.mp4")

    if not os.path.exists(input_video):
        print("❌ Missing:", vid)
        continue

    print("Processing:", vid)

    cap = cv2.VideoCapture(input_video)

    fps = cap.get(cv2.CAP_PROP_FPS)
    if fps == 0:
        fps = 25

    w = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    h = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))

    out = cv2.VideoWriter(
        output_video,
        cv2.VideoWriter_fourcc(*'mp4v'),
        fps,
        (w, h)
    )

    while True:
        ret, frame = cap.read()
        if not ret:
            break

        results = model(frame, verbose=False)

        wildlife = False
        human = False
        habitat = False

        for r in results:
            for box in r.boxes:
                cls = int(box.cls[0])
                conf = float(box.conf[0])
                label = model.names[cls]

                x1, y1, x2, y2 = map(int, box.xyxy[0])

                # Wildlife
                if label in wild_animals and conf > 0.4:
                    wildlife = True
                    cv2.rectangle(frame, (x1,y1), (x2,y2), (0,255,0), 2)
                    cv2.putText(frame, label, (x1,y1-5),
                                cv2.FONT_HERSHEY_SIMPLEX, 0.6, (0,255,0), 2)

                # Human
                if label == "person" and conf > 0.6:
                    human = True
                    cv2.rectangle(frame, (x1,y1), (x2,y2), (255,0,0), 2)
                    cv2.putText(frame, "Human", (x1,y1-5),
                                cv2.FONT_HERSHEY_SIMPLEX, 0.6, (255,0,0), 2)

                # Human habitat objects
                if label in human_objects and conf > 0.5:
                    habitat = True
                    cv2.rectangle(frame, (x1,y1), (x2,y2), (0,255,255), 2)
                    cv2.putText(frame, label, (x1,y1-5),
                                cv2.FONT_HERSHEY_SIMPLEX, 0.6, (0,255,255), 2)

        # ============================
        # Intrusion Decision
        # ============================
        status = "NORMAL"

        if wildlife and not human:
            status = "NO INTRUSION"
        elif wildlife and human and not habitat:
            status = "PARTIAL INTRUSION"
        elif wildlife and human and habitat:
            status = "INTRUSION"

        cv2.putText(frame, status, (30,40),
                    cv2.FONT_HERSHEY_SIMPLEX, 1, (0,0,255), 3)

        out.write(frame)

    cap.release()
    out.release()

    print("✅ Saved:", output_video)

print("🎉 ALL VIDEOS COMPLETED")

# ============================
# Mount Google Drive
# ============================
from google.colab import drive
drive.mount('/content/drive')

# ============================
# Install dependencies
# ============================
!pip install -q ultralytics opencv-python

from ultralytics import YOLO
import cv2
import os

# ============================
# Load YOLOv8
# ============================
model = YOLO("yolov8n.pt")

# ============================
# Videos list
# ============================
video_names = ["EDHH6.mp4", "EDHH5.mp4"]

base_path = "/content/drive/MyDrive"

# ============================
# YOLO classes
# ============================
wild_animals = [
    "elephant","bear","zebra","giraffe",
    "horse","sheep","cow","dog","cat","bird"
]

human_objects = ["car","truck","bus","motorbike","bicycle"]

# ============================
# Process each video
# ============================
for vid in video_names:

    input_video = os.path.join(base_path, vid)
    output_video = input_video.replace(".mp4", "_output.mp4")

    if not os.path.exists(input_video):
        print("❌ Missing:", vid)
        continue

    print("Processing:", vid)

    cap = cv2.VideoCapture(input_video)

    fps = cap.get(cv2.CAP_PROP_FPS)
    if fps == 0:
        fps = 25

    w = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    h = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))

    out = cv2.VideoWriter(
        output_video,
        cv2.VideoWriter_fourcc(*'mp4v'),
        fps,
        (w, h)
    )

    while True:
        ret, frame = cap.read()
        if not ret:
            break

        results = model(frame, verbose=False)

        wildlife = False
        human = False
        habitat = False

        for r in results:
            for box in r.boxes:
                cls = int(box.cls[0])
                conf = float(box.conf[0])
                label = model.names[cls]

                x1, y1, x2, y2 = map(int, box.xyxy[0])

                # Wildlife
                if label in wild_animals and conf > 0.4:
                    wildlife = True
                    cv2.rectangle(frame, (x1,y1), (x2,y2), (0,255,0), 2)
                    cv2.putText(frame, label, (x1,y1-5),
                                cv2.FONT_HERSHEY_SIMPLEX, 0.6, (0,255,0), 2)

                # Human
                if label == "person" and conf > 0.6:
                    human = True
                    cv2.rectangle(frame, (x1,y1), (x2,y2), (255,0,0), 2)
                    cv2.putText(frame, "Human", (x1,y1-5),
                                cv2.FONT_HERSHEY_SIMPLEX, 0.6, (255,0,0), 2)

                # Human habitat objects
                if label in human_objects and conf > 0.5:
                    habitat = True
                    cv2.rectangle(frame, (x1,y1), (x2,y2), (0,255,255), 2)
                    cv2.putText(frame, label, (x1,y1-5),
                                cv2.FONT_HERSHEY_SIMPLEX, 0.6, (0,255,255), 2)

        # ============================
        # Intrusion Decision
        # ============================
        status = "NORMAL"

        if wildlife and not human:
            status = "NO INTRUSION"
        elif wildlife and human and not habitat:
            status = "PARTIAL INTRUSION"
        elif wildlife and human and habitat:
            status = "INTRUSION"

        cv2.putText(frame, status, (30,40),
                    cv2.FONT_HERSHEY_SIMPLEX, 1, (0,0,255), 3)

        out.write(frame)

    cap.release()
    out.release()

    print("✅ Saved:", output_video)

print("🎉 ALL VIDEOS COMPLETED")

from google.colab import drive
drive.mount('/content/drive')

!pip install -q ultralytics opencv-python torchvision pillow

from ultralytics import YOLO
import cv2
import os
import torch
from torchvision import models, transforms
from PIL import Image

# ------------------------
# YOLO detector
# ------------------------
model = YOLO("yolov8n.pt")

# ------------------------
# Scene classifier (habitation)
# ------------------------
scene_model = models.resnet18(pretrained=True)
scene_model.eval()

scene_tf = transforms.Compose([
    transforms.Resize((224,224)),
    transforms.ToTensor()
])

# ------------------------
# Input videos
# ------------------------
video_names = ["EDH1.mp4","EDH2.mp4","EDH3.mp4","EDH4.mp4","EDHH6.mp4","EDHH5.mp4"]
base_path = "/content/drive/MyDrive"

wild_animals = [
    "elephant","bear","zebra","giraffe",
    "horse","sheep","cow","dog","cat","bird"
]

vehicle_classes = ["car","truck","bus","bicycle"]
motorcycle_class="motorcycle"

for vid in video_names:

    input_video=os.path.join(base_path,vid)
    output_video=input_video.replace(".mp4","_output.mp4")

    cap=cv2.VideoCapture(input_video)

    fps=cap.get(cv2.CAP_PROP_FPS)
    if fps==0: fps=25

    w=int(cap.get(3))
    h=int(cap.get(4))

    out=cv2.VideoWriter(output_video,
        cv2.VideoWriter_fourcc(*'mp4v'),fps,(w,h))

    while True:
        ret,frame=cap.read()
        if not ret: break

        results=model(frame,conf=0.25,verbose=False)

        wildlife=False
        human=False
        vehicle=False

        for r in results:
            for box in r.boxes:
                label=model.names[int(box.cls[0])]
                conf=float(box.conf[0])
                x1,y1,x2,y2=map(int,box.xyxy[0])

                if label in wild_animals and conf>0.45:
                    wildlife=True
                    cv2.rectangle(frame,(x1,y1),(x2,y2),(0,255,0),2)
                    cv2.putText(frame,label,(x1,y1-5),0,0.6,(0,255,0),2)

                elif label=="person" and conf>0.55:
                    human=True
                    cv2.rectangle(frame,(x1,y1),(x2,y2),(255,0,0),2)
                    cv2.putText(frame,"Human",(x1,y1-5),0,0.6,(255,0,0),2)

                elif label==motorcycle_class and conf>0.30:
                    vehicle=True
                    cv2.rectangle(frame,(x1,y1),(x2,y2),(0,255,255),2)
                    cv2.putText(frame,"Motorcycle",(x1,y1-5),0,0.6,(0,255,255),2)

                elif label in vehicle_classes and conf>0.30:
                    vehicle=True
                    cv2.rectangle(frame,(x1,y1),(x2,y2),(0,255,255),2)
                    cv2.putText(frame,"Vehicle",(x1,y1-5),0,0.6,(0,255,255),2)

        # ------------------------
        # Scene classification
        # ------------------------
        pil=Image.fromarray(cv2.cvtColor(frame,cv2.COLOR_BGR2RGB))
        inp=scene_tf(pil).unsqueeze(0)

        with torch.no_grad():
            pred=scene_model(inp)

        # Simple rule: vehicles or humans imply habitation
        habitation = True if (human or vehicle) else False

        place = "HABITATION" if habitation else "NON-HABITATION"

        cv2.putText(frame,f"Place: {place}",(30,70),
                    cv2.FONT_HERSHEY_SIMPLEX,0.8,(255,255,0),2)

        # ------------------------
        # Intrusion logic
        # ------------------------
        if wildlife and human and habitation:
            status="INTRUSION"
        elif wildlife and human:
            status="PARTIAL INTRUSION"
        elif wildlife:
            status="NO INTRUSION"
        else:
            status="NORMAL"

        cv2.putText(frame,status,(30,40),
                    cv2.FONT_HERSHEY_SIMPLEX,1.1,(0,0,255),3)

        out.write(frame)

    cap.release()
    out.release()
    print("Saved:",output_video)

print("ALL DONE")

"""# Task
The task is to integrate the YOLOv8 elephant and human detection logic (including confidence thresholds, drawing bounding boxes, and alert messages) into the `VideoTransformerBase` class for live camera feeds and into the video processing loop for uploaded files within the `app.py`, then run the Streamlit app and provide the public URL.

## Install Streamlit and Dependencies

### Subtask:
Install all necessary libraries, including `streamlit`, `streamlit-webrtc`, `opencv-python-headless`, and `ultralytics`, as well as `cloudflared` for creating a public URL for the app.

**Reasoning**:
I need to install the specified Python libraries and `cloudflared`. I will use `pip install` for the Python packages and `wget` to download `cloudflared` before installing it with `dpkg`.
"""

# Install libraries
!pip install streamlit streamlit-webrtc opencv-python-headless ultralytics
# Download stable tunneling tool
!wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
!dpkg -i cloudflared-linux-amd64.deb

"""## Create Streamlit App (app.py)

### Subtask:
Develop the `app.py` file to create the Streamlit interface, including sections for live camera input and video upload, and define a `VideoTransformer` class for live camera processing.

**Reasoning**:
I need to create the `app.py` file with the initial Streamlit structure, including imports, page configuration, a placeholder `VideoTransformer` class, and sections for live camera and video upload, as per the instructions.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import cv2
# import os
# import numpy as np
# import tempfile
# from streamlit_webrtc import webrtc_streamer, VideoTransformerBase, WebRtcMode
# from ultralytics import YOLO
# 
# # 1. Page Configuration
# st.set_page_config(
#     page_title="Elephant & Human Detection",
#     page_icon="🐘",
#     layout="wide"
# )
# 
# st.title("🐘 Live Elephant & Human Detection")
# st.markdown("--- Streamlit application for real-time object detection using YOLOv8 --- ")
# 
# # Global model instance for efficiency
# @st.cache_resource
# def load_yolo_model():
#     return YOLO("yolov8n.pt")
# 
# model = load_yolo_model()
# 
# # Define confidence thresholds
# ELEPHANT_CONF_GLOBAL = 0.45
# HUMAN_CONF_GLOBAL = 0.60
# 
# # 2. Define VideoTransformer for live camera feed
# class VideoTransformer(VideoTransformerBase):
#     def __init__(self):
#         self.model = model # Use the globally loaded model
#         self.elephant_conf = ELEPHANT_CONF_GLOBAL
#         self.human_conf = HUMAN_CONF_GLOBAL
# 
#     def transform(self, frame: np.ndarray) -> np.ndarray:
#         img = frame.copy() # Get the current frame
# 
#         results = self.model(img, verbose=False) # Run YOLOv8 inference
#         elephant_found = False
# 
#         for r in results:
#             for box in r.boxes:
#                 cls   = int(box.cls[0])
#                 conf  = float(box.conf[0])
#                 label = self.model.names[cls]
#                 x1, y1, x2, y2 = map(int, box.xyxy[0])
# 
#                 # ELEPHANT detection
#                 if label == "elephant" and conf >= self.elephant_conf:
#                     elephant_found = True
#                     cv2.rectangle(img, (x1, y1), (x2, y2),
#                                   (0, 255, 0), 2)
#                     cv2.putText(img,
#                                 f"Elephant {conf:.2f}",
#                                 (x1, y1 - 10),
#                                 cv2.FONT_HERSHEY_SIMPLEX,
#                                 0.9,
#                                 (0, 255, 0),
#                                 2)
# 
#                 # HUMAN detection
#                 elif label == "person" and conf >= self.human_conf:
#                     cv2.rectangle(img, (x1, y1), (x2, y2),
#                                   (255, 0, 0), 2)
#                     cv2.putText(img,
#                                 f"Human {conf:.2f}",
#                                 (x1, y1 - 10),
#                                 cv2.FONT_HERSHEY_SIMPLEX,
#                                 0.9,
#                                 (255, 0, 0),
#                                 2)
# 
#         # CAUTION ALERT
#         if elephant_found:
#             cv2.putText(img,
#                         "CAUTION: ELEPHANT DETECTED",
#                         (30, 50),
#                         cv2.FONT_HERSHEY_SIMPLEX,
#                         1.2,
#                         (0, 0, 255),
#                         3)
# 
#         return img
# 
# # Function to process uploaded videos
# def process_uploaded_video(input_video_path):
#     cap = cv2.VideoCapture(input_video_path)
# 
#     width  = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
#     height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
#     fps    = cap.get(cv2.CAP_PROP_FPS)
#     if fps == 0: fps = 25 # Default FPS if not detected
# 
#     # Create a temporary file for the output video
#     temp_output_file = tempfile.NamedTemporaryFile(delete=False, suffix='.mp4')
#     output_video_path = temp_output_file.name
#     temp_output_file.close()
# 
#     fourcc = cv2.VideoWriter_fourcc(*'mp4v')
#     out = cv2.VideoWriter(output_video_path, fourcc, fps, (width, height))
# 
#     progress_text = st.empty()
#     progress_bar = st.progress(0)
#     total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
#     processed_frames = 0
# 
#     while cap.isOpened():
#         ret, frame = cap.read()
#         if not ret:
#             break
# 
#         results = model(frame, verbose=False)
#         elephant_found = False
# 
#         for r in results:
#             for box in r.boxes:
#                 cls   = int(box.cls[0])
#                 conf  = float(box.conf[0])
#                 label = model.names[cls]
#                 x1, y1, x2, y2 = map(int, box.xyxy[0])
# 
#                 # ELEPHANT detection
#                 if label == "elephant" and conf >= ELEPHANT_CONF_GLOBAL:
#                     elephant_found = True
#                     cv2.rectangle(frame, (x1, y1), (x2, y2),
#                                   (0, 255, 0), 2)
#                     cv2.putText(frame,
#                                 f"Elephant {conf:.2f}",
#                                 (x1, y1 - 10),
#                                 cv2.FONT_HERSHEY_SIMPLEX,
#                                 0.9,
#                                 (0, 255, 0),
#                                 2)
# 
#                 # HUMAN detection
#                 elif label == "person" and conf >= HUMAN_CONF_GLOBAL:
#                     cv2.rectangle(frame, (x1, y1), (x2, y2),
#                                   (255, 0, 0), 2)
#                     cv2.putText(frame,
#                                 f"Human {conf:.2f}",
#                                 (x1, y1 - 10),
#                                 cv2.FONT_HERSHEY_SIMPLEX,
#                                 0.9,
#                                 (255, 0, 0),
#                                 2)
# 
#         # CAUTION ALERT
#         if elephant_found:
#             cv2.putText(frame,
#                         "CAUTION: ELEPHANT DETECTED",
#                         (30, 50),
#                         cv2.FONT_HERSHEY_SIMPLEX,
#                         1.2,
#                         (0, 0, 255),
#                         3)
# 
#         out.write(frame)
#         processed_frames += 1
#         progress_bar.progress(processed_frames / total_frames)
#         progress_text.text(f"Processing frame {processed_frames}/{total_frames}")
# 
#     cap.release()
#     out.release()
#     progress_text.empty()
#     progress_bar.empty()
# 
#     # Read the processed video into memory as bytes and delete the temporary file
#     with open(output_video_path, 'rb') as f:
#         video_bytes = f.read()
#     os.unlink(output_video_path) # Delete the temporary output file
# 
#     return video_bytes
# 
# # 3. Streamlit App Sections
# 
# tab1, tab2 = st.tabs(["Live Camera", "Upload Video"])
# 
# with tab1:
#     st.header("Live Camera Feed")
#     st.write("Start your camera to detect elephants and humans in real-time.")
# 
#     webrtc_ctx = webrtc_streamer(
#         key="yolo-detection",
#         mode=WebRtcMode.SENDRECV,
#         rtc_configuration={
#             "iceServers": [{"urls": ["stun:stun.l.google.com:19302"]}]}
#         ,
#         video_transformer_factory=VideoTransformer,
#         media_stream_constraints={
#             "video": True,
#             "audio": False
#         },
#         async_transform=True
#     )
# 
#     if webrtc_ctx.video_receiver:
#         st.success("Camera feed is active.")
#     else:
#         st.warning("Waiting for camera...")
# 
# with tab2:
#     st.header("Upload Video File")
#     st.write("Upload a video file to run detection.")
# 
#     uploaded_file = st.file_uploader("Choose a video file", type=["mp4", "avi", "mov"])
# 
#     if uploaded_file is not None:
#         st.video(uploaded_file, format="video/mp4")
#         st.success("Video uploaded successfully! Processing...")
# 
#         # Save the uploaded file to a temporary location
#         with tempfile.NamedTemporaryFile(delete=False, suffix='.mp4') as tfile:
#             tfile.write(uploaded_file.read())
#             video_path = tfile.name
# 
#         processed_video_bytes = process_uploaded_video(video_path)
# 
#         if processed_video_bytes:
#             st.subheader("Processed Video")
#             st.video(processed_video_bytes, format="video/mp4")
#             st.success("Video processing complete!")
#             os.unlink(video_path) # Clean up input temp file
#         else:
#             st.error("Video processing failed.")
# 
# 
# st.markdown("--- ")
# st.info("Note: Detection results will be displayed directly on the video feed.")

"""## Run Streamlit App and Expose Public URL

### Subtask:
Execute the Streamlit application in the background and use `cloudflared` to create a public, shareable URL, allowing you to access the frontend from any device.

**Reasoning**:
I need to run the Streamlit app in the background and then expose it using `cloudflared`. The `&` symbol will run the Streamlit app in the background, and then `cloudflared` will create a tunnel to expose the default Streamlit port (8501) to the internet, providing a public URL.
"""

import subprocess
import time
import re
import threading
from queue import Queue, Empty

# Define a function to read a stream and put lines into a queue
def enqueue_output(stream, queue):
    for line in iter(stream.readline, b''):
        queue.put(line)
    stream.close()

print("Starting Streamlit app in background...")
# Redirect Streamlit logs to files to keep console clean and avoid interference with cloudflared output
streamlit_log_file = open("streamlit_output.log", "w")
streamlit_error_file = open("streamlit_error.log", "w")
streamlit_process = subprocess.Popen(
    ["streamlit", "run", "app.py"],
    stdout=streamlit_log_file,
    stderr=streamlit_error_file
)

# Give Streamlit a moment to start up
time.sleep(5)

print("Starting cloudflared tunnel...")
# Use PIPE for stdout and stderr to capture the output for URL extraction
cloudflared_process = subprocess.Popen(
    ["cloudflared", "tunnel", "--url", "http://localhost:8501"],
    stdout=subprocess.PIPE,
    stderr=subprocess.PIPE
)

# Create queues for stdout and stderr
q_stdout = Queue()
q_stderr = Queue()

# Start reader threads for stdout and stderr
t_stdout = threading.Thread(target=enqueue_output, args=(cloudflared_process.stdout, q_stdout))
t_stderr = threading.Thread(target=enqueue_output, args=(cloudflared_process.stderr, q_stderr))

# Set threads as daemon so they terminate with the main program
t_stdout.daemon = True
t_stderr.daemon = True

t_stdout.start()
t_stderr.start()

# Regex to find the cloudflared public URL
url_pattern = re.compile(r"https://[a-zA-Z0-9-]+\.trycloudflare\.com")

public_url = None
start_time = time.time()
timeout_seconds = 60 # Max time to wait for the URL

print("Waiting for cloudflared public URL...")
while public_url is None and (time.time() - start_time) < timeout_seconds:
    # Check stdout queue
    try:
        line_bytes = q_stdout.get(timeout=0.1) # Blocks for a short time
        line = line_bytes.decode('utf-8').strip()
        print(f"[Cloudflared STDOUT] {line}") # Print all output for visibility
        match = url_pattern.search(line)
        if match:
            public_url = match.group(0)
            break
    except Empty:
        pass

    # Check stderr queue
    try:
        line_bytes = q_stderr.get(timeout=0.1) # Blocks for a short time
        line = line_bytes.decode('utf-8').strip()
        print(f"[Cloudflared STDERR] {line}") # Print all output for visibility
        match = url_pattern.search(line)
        if match:
            public_url = match.group(0)
            break
    except Empty:
        pass

    # Small delay before next check if nothing was read
    time.sleep(0.1)

# Report the found URL or lack thereof
if public_url:
    print(f"\n🎉 Streamlit app is accessible at: {public_url}\n")
else:
    print(f"\n❌ Could not find cloudflared URL within {timeout_seconds} seconds. Please check the 'cloudflared_stderr.log' and 'cloudflared_stdout.log' files for more details or try again.")

# The original code ended with a `while True: time.sleep(60)` to keep the colab cell alive
# and thus keep the subprocesses running. This behavior is retained.
print("\nKeeping the Streamlit app and Cloudflared tunnel running. You can interact with the app via the URL above.")
print("To stop the processes, interrupt this cell's execution.")
while True:
    time.sleep(60)

"""# Task
The `app.py` file has been updated to return the processed video as bytes, and the Streamlit UI now displays these bytes directly.

Now, I will execute the `app.py` file in the background and use `cloudflared` to expose a public URL for the updated Streamlit application. This will allow us to test if the video upload and display functionality works correctly.
```python
%%writefile app.py
import streamlit as st
import cv2
import os
import numpy as np
import tempfile
from streamlit_webrtc import webrtc_streamer, VideoTransformerBase, WebRtcMode
from ultralytics import YOLO

# 1. Page Configuration
st.set_page_config(
    page_title="Elephant & Human Detection",
    page_icon="🐘",
    layout="wide"
)

st.title("🐘 Live Elephant & Human Detection")
st.markdown("--- Streamlit application for real-time object detection using YOLOv8 --- ")

# Global model instance for efficiency
@st.cache_resource
def load_yolo_model():
    return YOLO("yolov8n.pt")

model = load_yolo_model()

# Define confidence thresholds
ELEPHANT_CONF_GLOBAL = 0.45
HUMAN_CONF_GLOBAL = 0.60

# 2. Define VideoTransformer for live camera feed
class VideoTransformer(VideoTransformerBase):
    def __init__(self):
        self.model = model # Use the globally loaded model
        self.elephant_conf = ELEPHANT_CONF_GLOBAL
        self.human_conf = HUMAN_CONF_GLOBAL

    def transform(self, frame: np.ndarray) -> np.ndarray:
        img = frame.copy() # Get the current frame

        results = self.model(img, verbose=False) # Run YOLOv8 inference
        elephant_found = False

        for r in results:
            for box in r.boxes:
                cls   = int(box.cls[0])
                conf  = float(box.conf[0])
                label = self.model.names[cls]
                x1, y1, x2, y2 = map(int, box.xyxy[0])

                # ELEPHANT detection
                if label == "elephant" and conf >= self.elephant_conf:
                    elephant_found = True
                    cv2.rectangle(img, (x1, y1), (x2, y2),
                                  (0, 255, 0), 2)
                    cv2.putText(img,
                                f"Elephant {conf:.2f}",
                                (x1, y1 - 10),
                                cv2.FONT_HERSHEY_SIMPLEX,
                                0.9,
                                (0, 255, 0),
                                2)

                # HUMAN detection
                elif label == "person" and conf >= self.human_conf:
                    cv2.rectangle(img, (x1, y1), (x2, y2),
                                  (255, 0, 0), 2)
                    cv2.putText(img,
                                f"Human {conf:.2f}",
                                (x1, y1 - 10),
                                cv2.FONT_HERSHEY_SIMPLEX,
                                0.9,
                                (255, 0, 0),
                                2)

        # CAUTION ALERT
        if elephant_found:
            cv2.putText(img,
                        "CAUTION: ELEPHANT DETECTED",
                        (30, 50),
                        cv2.FONT_HERSHEY_SIMPLEX,
                        1.2,
                        (0, 0, 255),
                        3)

        return img

# Function to process uploaded videos
def process_uploaded_video(input_video_path):
    cap = cv2.VideoCapture(input_video_path)

    width  = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
    fps    = cap.get(cv2.CAP_PROP_FPS)
    if fps == 0: fps = 25 # Default FPS if not detected

    # Create a temporary file for the output video
    with tempfile.NamedTemporaryFile(delete=False, suffix='.mp4') as temp_output_file:
        output_video_path = temp_output_file.name

    fourcc = cv2.VideoWriter_fourcc(*'mp4v')
    out = cv2.VideoWriter(output_video_path, fourcc, fps, (width, height))

    progress_text = st.empty()
    progress_bar = st.progress(0)
    total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
    processed_frames = 0

    while cap.isOpened():
        ret, frame = cap.read()
        if not ret:
            break

        results = model(frame, verbose=False)
        elephant_found = False

        for r in results:
            for box in r.boxes:
                cls   = int(box.cls[0])
                conf  = float(box.conf[0])
                label = model.names[cls]
                x1, y1, x2, y2 = map(int, box.xyxy[0])

                # ELEPHANT detection
                if label == "elephant" and conf >= ELEPHANT_CONF_GLOBAL:
                    elephant_found = True
                    cv2.rectangle(frame, (x1, y1), (x2, y2),
                                  (0, 255, 0), 2)
                    cv2.putText(frame,
                                f"Elephant {conf:.2f}",
                                (x1, y1 - 10),
                                cv2.FONT_HERSHEY_SIMPLEX,
                                0.9,
                                (0, 255, 0),
                                2)

                # HUMAN detection
                elif label == "person" and conf >= HUMAN_CONF_GLOBAL:
                    cv2.rectangle(frame, (x1, y1), (x2, y2),
                                  (255, 0, 0), 2)
                    cv2.putText(frame,
                                f"Human {conf:.2f}",
                                (x1, y1 - 10),
                                cv2.FONT_HERSHEY_SIMPLEX,
                                0.9,
                                (255, 0, 0),
                                2)

        # CAUTION ALERT
        if elephant_found:
            cv2.putText(frame,
                        "CAUTION: ELEPHANT DETECTED",
                        (30, 50),
                        cv2.FONT_HERSHEY_SIMPLEX,
                        1.2,
                        (0, 0, 255),
                        3)

        out.write(frame)
        processed_frames += 1
        progress_bar.progress(processed_frames / total_frames)
        progress_text.text(f"Processing frame {processed_frames}/{total_frames}")

    cap.release()
    out.release()
    progress_text.empty()
    progress_bar.empty()

    # Read the processed video into memory
    with open(output_video_path, 'rb') as f:
        video_bytes = f.read()

    # Clean up the temporary output file
    os.unlink(output_video_path)

    return video_bytes

# 3. Streamlit App Sections

tab1, tab2 = st.tabs(["Live Camera", "Upload Video"])

with tab1:
    st.header("Live Camera Feed")
    st.write("Start your camera to detect elephants and humans in real-time.")

    webrtc_ctx = webrtc_streamer(
        key="yolo-detection",
        mode=WebRtcMode.SENDRECV,
        rtc_configuration={
            "iceServers": [{"urls": ["stun:stun.l.google.com:19302"]}]}
        ,
        video_transformer_factory=VideoTransformer,
        media_stream_constraints={
            "video": True,
            "audio": False
        },
        async_transform=True
    )

    if webrtc_ctx.video_receiver:
        st.success("Camera feed is active.")
    else:
        st.warning("Waiting for camera...")

with tab2:
    st.header("Upload Video File")
    st.write("Upload a video file to run detection.")

    uploaded_file = st.file_uploader("Choose a video file", type=["mp4", "avi", "mov"])

    if uploaded_file is not None:
        st.video(uploaded_file, format="video/mp4")
        st.success("Video uploaded successfully! Processing...")

        # Save the uploaded file to a temporary location
        with tempfile.NamedTemporaryFile(delete=False, suffix='.mp4') as tfile:
            tfile.write(uploaded_file.read())
            video_path = tfile.name

        processed_video_bytes = process_uploaded_video(video_path)

        if processed_video_bytes:
            st.subheader("Processed Video")
            st.video(processed_video_bytes, format="video/mp4")
            st.success("Video processing complete!")
            os.unlink(video_path) # Clean up input temp file
        else:
            st.error("Video processing failed.")


st.markdown("--- ")
st.info("Note: Detection results will be displayed directly on the video feed.")
```
```python
import subprocess
import time
import re
import threading
from queue import Queue, Empty

# Define a function to read a stream and put lines into a queue
def enqueue_output(stream, queue):
    for line in iter(stream.readline, b''):
        queue.put(line)
    stream.close()

print("Starting Streamlit app in background...")
# Redirect Streamlit logs to files to keep console clean and avoid interference with cloudflared output
streamlit_log_file = open("streamlit_output.log", "w")
streamlit_error_file = open("streamlit_error.log", "w")
streamlit_process = subprocess.Popen(
    ["streamlit", "run", "app.py"],
    stdout=streamlit_log_file,
    stderr=streamlit_error_file
)

# Give Streamlit a moment to start up
time.sleep(5)

print("Starting cloudflared tunnel...")
# Use PIPE for stdout and stderr to capture the output for URL extraction
cloudflared_process = subprocess.Popen(
    ["cloudflared", "tunnel", "--url", "http://localhost:8501"],
    stdout=subprocess.PIPE,
    stderr=subprocess.PIPE
)

# Create queues for stdout and stderr
q_stdout = Queue()
q_stderr = Queue()

# Start reader threads for stdout and stderr
t_stdout = threading.Thread(target=enqueue_output, args=(cloudflared_process.stdout, q_stdout))
t_stderr = threading.Thread(target=enqueue_output, args=(cloudflared_process.stderr, q_stderr))

# Set threads as daemon so they terminate with the main program
t_stdout.daemon = True
t_stderr.daemon = True

t_stdout.start()
t_stderr.start()

# Regex to find the cloudflared public URL
url_pattern = re.compile(r"https://[a-zA-Z0-9-]+\.trycloudflare\.com")

public_url = None
start_time = time.time()
timeout_seconds = 60 # Max time to wait for the URL

print("Waiting for cloudflared public URL...")
while public_url is None and (time.time() - start_time) < timeout_seconds:
    # Check stdout queue
    try:
        line_bytes = q_stdout.get(timeout=0.1) # Blocks for a short time
        line = line_bytes.decode('utf-8').strip()
        print(f"[Cloudflared STDOUT] {line}") # Print all output for visibility
        match = url_pattern.search(line)
        if match:
            public_url = match.group(0)
            break
    except Empty:
        pass

    # Check stderr queue
    try:
        line_bytes = q_stderr.get(timeout=0.1) # Blocks for a short time
        line = line_bytes.decode('utf-8').strip()
        print(f"[Cloudflared STDERR] {line}") # Print all output for visibility
        match = url_pattern.search(line)
        if match:
            public_url = match.group(0)
            break
    except Empty:
        pass

    # Small delay before next check if nothing was read
    time.sleep(0.1)

# Report the found URL or lack thereof
if public_url:
    print(f"\n🎉 Streamlit app is accessible at: {public_url}\n")
else:
    print(f"\n❌ Could not find cloudflared URL within {timeout_seconds} seconds. Please check the 'cloudflared_stderr.log' and 'cloudflared_stdout.log' files for more details or try again.")

# The original code ended with a `while True: time.sleep(60)` to keep the colab cell alive
# and thus keep the subprocesses running. This behavior is retained.
print("\nKeeping the Streamlit app and Cloudflared tunnel running. You can interact with the app via the URL above.")
print("To stop the processes, interrupt this cell's execution.")
while True:
    time.sleep(60)
```
```text
The Streamlit app is now running with the updated video display logic. Please navigate to the following URL in your web browser to test the functionality:

https://reaction-pdt-yea-early.trycloudflare.com

Verify that uploaded videos process correctly and are displayed within the Streamlit application.
```

## Modify app.py for video display

### Subtask:
Update the `process_uploaded_video` function in `app.py` to read the processed video into memory as bytes before deleting the temporary file. The function will then return these bytes. The Streamlit UI code will be updated to receive these bytes and pass them directly to `st.video` for display.

**Reasoning**:
The `app.py` file has been updated to return the processed video as bytes, and the Streamlit UI now displays these bytes directly. Now, I will execute the `app.py` file in the background and use `cloudflared` to expose a public URL for the updated Streamlit application. This will allow us to test if the video upload and display functionality works correctly.
"""

import subprocess
import time
import re
import threading
from queue import Queue, Empty

# Define a function to read a stream and put lines into a queue
def enqueue_output(stream, queue):
    for line in iter(stream.readline, b''):
        queue.put(line)
    stream.close()

print("Starting Streamlit app in background...")
# Redirect Streamlit logs to files to keep console clean and avoid interference with cloudflared output
streamlit_log_file = open("streamlit_output.log", "w")
streamlit_error_file = open("streamlit_error.log", "w")
streamlit_process = subprocess.Popen(
    ["streamlit", "run", "app.py"],
    stdout=streamlit_log_file,
    stderr=streamlit_error_file
)

# Give Streamlit a moment to start up
time.sleep(5)

print("Starting cloudflared tunnel...")
# Use PIPE for stdout and stderr to capture the output for URL extraction
cloudflared_process = subprocess.Popen(
    ["cloudflared", "tunnel", "--url", "http://localhost:8501"],
    stdout=subprocess.PIPE,
    stderr=subprocess.PIPE
)

# Create queues for stdout and stderr
q_stdout = Queue()
q_stderr = Queue()

# Start reader threads for stdout and stderr
t_stdout = threading.Thread(target=enqueue_output, args=(cloudflared_process.stdout, q_stdout))
t_stderr = threading.Thread(target=enqueue_output, args=(cloudflared_process.stderr, q_stderr))

# Set threads as daemon so they terminate with the main program
t_stdout.daemon = True
t_stderr.daemon = True

t_stdout.start()
t_stderr.start()

# Regex to find the cloudflared public URL
url_pattern = re.compile(r"https://[a-zA-Z0-9-]+\.trycloudflare\.com")

public_url = None
start_time = time.time()
timeout_seconds = 60 # Max time to wait for the URL

print("Waiting for cloudflared public URL...")
while public_url is None and (time.time() - start_time) < timeout_seconds:
    # Check stdout queue
    try:
        line_bytes = q_stdout.get(timeout=0.1) # Blocks for a short time
        line = line_bytes.decode('utf-8').strip()
        print(f"[Cloudflared STDOUT] {line}") # Print all output for visibility
        match = url_pattern.search(line)
        if match:
            public_url = match.group(0)
            break
    except Empty:
        pass

    # Check stderr queue
    try:
        line_bytes = q_stderr.get(timeout=0.1) # Blocks for a short time
        line = line_bytes.decode('utf-8').strip()
        print(f"[Cloudflared STDERR] {line}") # Print all output for visibility
        match = url_pattern.search(line)
        if match:
            public_url = match.group(0)
            break
    except Empty:
        pass

    # Small delay before next check if nothing was read
    time.sleep(0.1)

# Report the found URL or lack thereof
if public_url:
    print(f"\n🎉 Streamlit app is accessible at: {public_url}\n")
else:
    print(f"\n❌ Could not find cloudflared URL within {timeout_seconds} seconds. Please check the 'cloudflared_stderr.log' and 'cloudflared_stdout.log' files for more details or try again.")

# The original code ended with a `while True: time.sleep(60)` to keep the colab cell alive
# and thus keep the subprocesses running. This behavior is retained.
print("\nKeeping the Streamlit app and Cloudflared tunnel running. You can interact with the app via the URL above.")
print("To stop the processes, interrupt this cell's execution.")
while True:
    time.sleep(60)
